resources:
- repo: self
  fetchDepth: 15
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
  - vstest

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1


- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'src/SQLCover/SQLCover.sln'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: 'src/SQLCover/SQLCover.sln'

    platform: 'Any CPU'

    configuration: 'Release'

- task: VSTest@2
  displayName: 'Unit Tests'
  inputs:
    pathtoCustomTestAdapters: 'src/SQLCover/packages'
    testAssemblyVer2: |
     **\*UnitTests*.dll
    platform: 'Any CPU'
    configuration: 'Release'

- task: PowerShell@2
  displayName: 'Create Docker Sql'
  inputs:
    filePath: 'src\SQLCover\test\CreateDockerDbInstance.ps1'


- task: PowerShell@2
  displayName: 'Deploy Test Databases to Sql Local Db'
  inputs:
    filePath: 'src\SQLCover\test\deployLocal.ps1'
    arguments: '-configuration Release'


- task: VSTest@2
  displayName: 'Integration Tests'
  inputs:
    pathtoCustomTestAdapters: 'src/SQLCover/packages'
    testAssemblyVer2: |
     **\*IntegrationTests*.dll
    platform: 'Any CPU'
    configuration: 'Release'


- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'

    Contents: '**\bin\$(BuildConfiguration)\**'

    TargetFolder: '$(build.artifactstagingdirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'


